### PR TITLE
Write API endpoint for POST, RETRIEVE AND LISTING EVENTS

### PR DESCRIPTION
**Pull request by Konlan21**

### CODE REVIEW

**Review by solutionasepe — COMMENTED** [review]
Sorry, i have to say this, there is a model that you can use,  you can delete this model you just created. and in the url you created, you have two urls that are the same. events/, pls resolve it

**Comment by Konlan21** [comment]
Okay resolving the issue

**Comment by solutionasepe** [comment]
> Okay resolving the issue

the url path you can leave it that way since it's different method, but resolve the concerning the models

**Comment by Konlan21** [comment]
Models issue resolved

**Comment by Pythonian** [comment]
Please @solutionasepe can you help with another review, so that we can now have this merged. Thanks a lot.

**Pull request merged**
