### PR TITLE
Create new group/feature

### PR DESCRIPTION
**Pull request by breezeconcept**
## Description

This pull request introduces enhancements and updates to the `GroupViewSet` in the `groups` app. The primary changes include the implementation of a new feature for creating groups via a POST request to the `/api/groups` endpoint. The changes ensure that users can provide group details, validate the input data, create a new group in the database, and assign the user who created the group as the group's owner or administrator.

## Related Issue

This pull request is related to issue #57. The issue outlines the requirement and context for this feature.

## Motivation and Context

The changes introduced in this pull request are required to fulfill the acceptance criteria outlined in the related issue. The motivation behind these changes is to enhance the functionality of the `GroupViewSet` by allowing users to create groups programmatically through the API.

## How Has This Been Tested?

The following testing procedures were undertaken to validate the changes:

- **Unit Tests:** New unit tests have been added to ensure that the new group creation functionality works as expected. These tests cover both valid and invalid input cases.

- **Manual Testing:** The API endpoint `/api/groups` was manually tested using tools like Postman. Valid input data was used to create new groups, and the response was examined for correctness. Invalid input data was also tested to verify that proper validation errors are returned.

- **Integration Testing:** The changes were integrated into the existing project, and the entire application was tested to ensure that the new functionality does not introduce regressions.

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by olatunde2** [comment]
Please check the update version before you push

**Comment by breezeconcept** [comment]
> Please check the update version before you push

> Done

**Comment by olatunde2** [comment]
Please check the latest update before you push

**Comment by breezeconcept** [comment]
Conflicts resolved

**Pull request merged**
